# Generated by Django 4.2.7 on 2025-10-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0050_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
