# Generated by Django 4.2.7 on 2025-11-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0076_alter_orders_status_superadmin'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['status'], name='ecom_orders_status_7d7f52_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['created_at'], name='ecom_orders_created_089f00_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['status', 'created_at'], name='ecom_orders_status_9035d7_idx'),
        ),
    ]
