# Generated by Django 4.2.7 on 2025-11-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0077_orders_ecom_orders_status_7d7f52_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='External delivery tracking link', max_length=500, null=True),
        ),
    ]
