# Generated by Django 4.2.7 on 2025-11-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0078_orders_tracking_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
