# Generated by Django 4.2.7 on 2025-11-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0079_product_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gcash_reference_id',
            field=models.CharField(blank=True, help_text='GCash reference ID from provider (non-sensitive)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_gcash_txn_id',
            field=models.CharField(blank=True, help_text='Last GCash transaction ID captured', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_paypal_txn_id',
            field=models.CharField(blank=True, help_text='Last PayPal transaction ID captured', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='paypal_email',
            field=models.EmailField(blank=True, help_text='PayPal email from last successful payment', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='paypal_payer_id',
            field=models.CharField(blank=True, help_text='PayPal Payer ID (non-sensitive)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('paypal', 'PayPal'), ('gcash', 'GCash')], default='cod', help_text='Customer preferred payment method', max_length=10),
        ),
    ]
