# Generated by Django 4.2.7 on 2025-11-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0080_customer_gcash_reference_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorderitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.CharField(choices=[('NCR', 'National Capital Region')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending - Awaiting Payment'), ('Processing', 'Payment Confirmed - In Production'), ('Order Confirmed', 'Order Confirmed - In Production'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancellation Requested', 'Waiting for approval of Cancellation'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Current status of the order', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='region',
            field=models.CharField(choices=[('NCR', 'National Capital Region')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('customer', 'product')},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
    ]
